packages <- c("ggplot2", "dplyr", "broom", "ggpubr", "readxl", "writexl")
install.packages(setdiff(packages, rownames(installed.packages())))  
setwd('~/COVID19_hospitalizations-death/')
deaths <- read_excel("united_states_covid19_cases_deaths_and_testing_by_state_states only.xlsx")
govenors<- read_excel("US govenors party 2020.xlsx")
age<-read_excel('US state median population.xlsx')
gini<-read_excel('gini index.xlsx')
beds<-read.csv("states_beds_per1000.csv")
beds<-beds[c(1,5)]
deaths<- deaths[c(1,7)]
final1<- merge(deaths, govenors, by = "State")
final2 <- merge(gini, age, by = "State")
final <- merge(final1, final2, by = "State")
final <- merge(final,beds,by="State")
write_xlsx(x = final, path = "final.xlsx")
summary(final)
hist(final$`Death Rate per 100000`)
hist(final$`Total_beds_per1000`)
plot(`Total_beds_per1000` ~ `Death Rate per 100000`, data = final)
cor(final$`Total_beds_per1000`, final$`Death Rate per 100000`)
bed.lm <- lm(`Total_beds_per1000` ~ `Death Rate per 100000`, data = final)
age.lm <-  lm(`MedianAge` ~ `Death Rate per 100000`, data = final)
gini.lm <- lm(`Gini Index` ~ `Death Rate per 100000`, data = final)
summary(bed.lm)
summary(age.lm)
summary(gini.lm)
